import AdminNavbar from "@/components/AdminNavbar";
import "@/styles/globals.css";
//import Provider from "../Provider";

export const metadata = {
  title: "Admin",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  pageProps: any;
}) {
  return (
    <html lang="en">
      <body>
        <AdminNavbar />
        <main className="flex justify-center border">{children}</main>
      </body>
    </html>
  );
}
