import Title from "@/components/Title";
import AdminNavbar from "@/components/admin/AdminNavbar";
import LoginButton from "@/components/admin/Button";
import { authOptions } from "@/lib/auth";

import { getServerSession } from "next-auth";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Admin",
  description: "Generated by Next.js",
};

export default async function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (!session)
    return (
      <div className="flex flex-col h-screen w-full items-center justify-center py-5 gap-5">
        <Title title="Not authenticated" />
        <LoginButton />
      </div>
    );

  return (
    <>
      <AdminNavbar />
      <div className="flex justify-center items-start h-full w-full">
        {children}
      </div>
    </>
  );
}
